$script = <<-SCRIPT
yum clean all
yum install httpd -y
systemctl enable httpd
systemctl start httpd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.6"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: $script
end
