---
driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

# transport:
#   name: winrm
#   elevated: true
#   username: Administrator
#   password: Pass@word1

platforms:
  - name: my-windows-2016
    driver:
      customize:
        memory: 2048
      # box: mwrock/Windows2016
      box: mwrock/Windows2016

suites:
  - name: default
    run_list:
      - recipe[example-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
