---
driver:
  name: vagrant
  boot_timeout: 1200
  gui: false

provisioner:
  name: chef_zero
  product_version: "14.12"
  install_strategy: always

verifier:
  name: inspec

platforms:
  - name: windows2016
    driver:
      box: mwrock/Windows2016
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[example-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
