name 'my_cb_a'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures my_cb_a'
long_description 'Installs/Configures my_cb_a'
version '0.1.0'
chef_version '>= 14.0'

depends 'motd'
