Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.6"

  config.vm.provision "chef_zero" do |chef|
    chef.arguments = '--chef-license accept'
    chef.nodes_path = './nodes'
  end
end
