Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2016"

  config.vm.guest = :windows
  config.vm.communicator = :winrm

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.memory = 3072
  end
end
