---

driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec

platforms:
  - name: bento/centos-7.6

suites:
  - name: web-dev
    attributes:
      myrole: web
      myenvironment: dev
    provisioner:
      policyfile: Policyfile.rb
    verifier:
      inspec_tests:
        - test/integration/default
